FROM ubuntu:22.10

# Copiar scripts y archivos necesarios
COPY entrypoint.sh .
COPY sources.list /etc/apt/

# Actualizar los repositorios y instalar dependencias necesarias
RUN apt-get update && \
    apt-get install -y build-essential zlib1g-dev libssl-dev libpam0g-dev libselinux1-dev wget  
    ## apt-get install -y tshark

# Crear usuario prueba
ARG USER=prueba
ARG PASS="prueba"
RUN useradd -m -s /bin/bash $USER && echo "$USER:$PASS" | chpasswd

# Descargar el código fuente de OpenSSH
RUN wget https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-9.0p1.tar.gz && \
    tar -xzf openssh-9.0p1.tar.gz

# Modificar el número de versión
RUN cd openssh-9.0p1 && \
    sed -i 's/^#define SSH_VERSION.*/#define SSH_VERSION "OpenSSH_?"/' version.h && \
    ./configure && \
    make && \
    make install

# Hacer el script de entrada ejecutable
RUN chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
