FROM ubuntu:22.10

COPY entrypoint.sh .
COPY sources.list /etc/apt/

RUN apt-get update
RUN apt-get install -y wireshark


# Creación de usuario prueba
ARG USER=prueba
ARG PASS="prueba"
RUN useradd -m -s /bin/bash $USER && echo "$USER:$PASS" | chpasswd

# Instalación de SSH
RUN apt-get install -y openssh-client openssh-server

ENTRYPOINT ["./entrypoint.sh"]
