FROM ubuntu:16.10

COPY sources.list /etc/apt/

RUN apt-get update
RUN apt-get install -y openssh-client openssh-server

# Para que el contenedor siga en ejecución
ENTRYPOINT ["tail", "-f", "/dev/null"]
